ARG from=ubuntu:latest
FROM ${from}
RUN \
    apt-get update && \
    apt-get -y install g++-aarch64-linux-gnu gdb-multiarch pkg-config-aarch64-linux-gnu && \
    apt-get -y autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/*
